dist: xenial
language: python
python:
  - 3.6
  - 3.7
install:
  - make install-deps
script:
  - make ci
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/41f59acc-412b-11e9-baf0-0a580a281a0a/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
after_script:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "mime/type" path/to/artifact
