dist: xenial
language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements-dev.txt
script:
  - echo '--- code style checking ---'
  - flake8 discovery/*.py
  - flake8 tests/*.py
  - echo '--- unittest ---'
  - python -m pytest -v --cov=tests
