language: python
python:
  - 3.6.8
  - 3.7.2
install:
  - pip install -r requirements-dev.txt
script:
  - echo '--- code style checking ---'
  - flake8 discovery/*.py
  - echo '--- unittest ---'
  - python -m pytest -v
