version: '3'
services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
      - 8300:8300
        #  client:
        #    image: consul
        #    container_name: consul_client
        #    ports:
        #      - 8500:8500
        #      - 8600:8600/tcp
        #      - 8600:8600/udp
        #      #- 8501:8501 # HTTP off by default
        #      - 8502:8502
        #
