version: '3'
services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
      - 8300:8300
    extra_hosts:
      - "aio-client:${HOST_ADDRESS}"
      - "httpx-client:${HOST_ADDRESS}"
