version: '2'
services:
  discovery:
    image: consul
    container_name: discovery
    ports:
      - 8500:8500
    # extra_hosts:
    #   - "aio-client:MY_IP"
    #   - "standard-client:MY_IP"
  standard-client:
    build:
      context: .
      dockerfile: Dockerfile-client
    container_name: standard-client
    ports:
      - 5001:5000
  aio-client:
    build:
      context: .
      dockerfile: Dockerfile-aio
    container_name: aio-client
    ports:
      - 5002:5000
