"""Test Consul standard client module."""

import logging
import unittest
from unittest.mock import MagicMock
from unittest.mock import patch

import consul

from discovery import check, client, service
from discovery.utils import select_one_random

import requests


class TestClient(unittest.TestCase):
    """Unit tests to Consul standard client."""

    @patch('discovery.client.consul.Consul')
    def setUp(self, MockConsul):
        """Mock of responses generated by python-consul.

        and expected results generated by discovery-client.
        """
        self.consul_health_response = (
            0, [{'Node': {
                'ID': '123456',
                'Address': '127.0.0.1'}}])
        self.consul_raw_response = (
            0, [{'Node': 'localhost',
                 'ID': '5d9f029a-ee3f-b8b6-61a9-4042ad43e968',
                 'Address': '127.0.0.1',
                 'ServiceID': '#123',
                 'ServiceName': 'consul',
                 'ServicePort': 8300}])
        self.myapp_raw_response = (
            0, [{'Node': 'localhost',
                 'ID': '5d9f029a-ee3f-b8b6-61a9-4042ad43e968',
                 'Address': '127.0.0.1',
                 'ServiceID': '#987',
                 'ServiceName': 'myapp',
                 'ServicePort': 5000}])
        self.fmt_response = [
            {
                'node': 'localhost',
                'node_id': '5d9f029a-ee3f-b8b6-61a9-4042ad43e968',
                'address': '127.0.0.1',
                'service_id': '#123',
                'service_name': 'consul',
                'service_port': 8300
            },
            {
                'node': 'localhost',
                'node_id': '5d9f029a-ee3f-b8b6-61a9-4042ad43e968',
                'address': '127.0.0.1',
                'service_id': '#987',
                'service_name': 'myapp',
                'service_port': 5000
            }]
        self.consul_client = MockConsul(consul.Consul)
        self.consul_client.agent.service.register = MagicMock()
        self.consul_client.agent.service.deregister = MagicMock()
        self.consul_client.agent.check.register = MagicMock()
        self.consul_client.agent.check.deregister = MagicMock()
        self.consul_client.catalog.service = MagicMock(
            return_value=self.consul_raw_response
        )
        self.consul_client.status.leader = MagicMock(
            return_value='127.0.0.1:8300'
        )
        self.consul_client.health.service = MagicMock(
            return_value=self.consul_health_response
        )
        self.svc = service.Service(
            'myapp',
            5000,
            check=check.Check('test-check', check.alias('consul'))
        )
        self.dc = client.Consul()
        self.dc.service = self.svc

    def tearDown(self):
        self.dc.timeout = 30

    def test_default_timeout(self):
        """Test default timeout used to check periodically health status of the Consul connection."""
        self.assertEqual(self.dc.timeout, 30)

    def test_changing_default_timeout(self):
        """Test change the time used to check periodically health status of the Consul connection."""
        self.dc.timeout = '5'
        self.assertEqual(self.dc.timeout, 5)

    def test_find_services(self):
        """Test for localization of a set of services present in the consul's catalog.

        Return a list of instances present in the consul's catalog.
        """
        consul_service = self.dc.find_services('consul')

        self.assertIsInstance(consul_service, list)
        self.assertIn(consul_service[0].raw, self.fmt_response)

    def test_find_services_not_on_catalog(self):
        """Test for localization of a set of services not present in the consul's catalog.

        Return a empty list.
        """
        self.consul_client.catalog.service = MagicMock(return_value=(0, []))
        response = self.dc.find_services('myapp')

        self.assertEqual(response, [])

    def test_find_service_not_found(self):
        """Test for localization of a service not present in the consul's catalog.

        Raise IndexError execption.
        """
        self.consul_client.catalog.service = MagicMock(return_value=(0, []))
        with self.assertRaises(IndexError):
            self.dc.find_service('myapp')

    def test_find_service_rr(self):
        """Test for localization of a service present in the consul's catalog.

        Return instances in round robin method, when there is more than
        one registered.
        """
        consul_service = self.dc.find_service('consul', select_one_random)

        self.assertIsInstance(consul_service, service.Service)
        self.assertEqual(consul_service.raw, self.fmt_response[0])

    def test_find_service_random(self):
        """Test for localization of a service present in the consul's catalog.

        Return random instances, when there is more than one registered.
        """
        consul_service = self.dc.find_service('consul', select_one_random)

        self.assertIsInstance(consul_service, service.Service)
        self.assertEqual(consul_service.raw, self.fmt_response[0])

    def test_register(self):
        """Test registration of a service in the  consul's catalog."""
        self.dc.register()
        myapp_service = self.dc.find_service('myapp')

        self.assertIsInstance(myapp_service, service.Service)
        self.assertIn(myapp_service.raw, self.fmt_response)

    def test_register_connection_error(self):
        """Failure test to register a service when there is no instance of consul available."""
        self.consul_client.agent.service.register = MagicMock(
            side_effect=requests.exceptions.ConnectionError
        )
        self.consul_client.health.service = MagicMock(
            side_effect=requests.exceptions.ConnectionError
        )

        with self.assertLogs() as cm:
            logging.getLogger(self.dc.register())
        self.assertEqual(
            cm.output, ['ERROR:root:Failed to connect to discovery...']
        )

    def test_deregister(self):
        """Test the deregistration of a service present in the consul's catalog."""
        self.dc.register()
        myapp_service = self.dc.find_service('myapp')

        self.assertIsInstance(myapp_service, service.Service)
        self.assertIn(myapp_service.raw, self.fmt_response)

        self.dc.deregister()

        self.consul_client.catalog.service = MagicMock(return_value=(0, []))

        with self.assertRaises(IndexError):
            myapp_service = self.dc.find_service('myapp')

    def test_register_additional_check(self):
        """Test the registration of an additional check for a service registered."""
        self.dc.register_additional_check(
            check.Check(
                name='additional-check',
                check=check.alias('consul')
            )
        )

    def test_register_additional_check_failed(self):
        with self.assertRaises(TypeError):
            self.dc.register_additional_check('invalid-check')
